language: node_js
node_js:
  - "5.0.0"
before_script:
  - npm install -g gulp
script: gulp test
deploy:
  provider: heroku
  api_key:
     secure: f9f77f2e-b88a-4f45-8c10-d9a8ccb4e930
  on: 
     branch: master
